name: Flooring by Cogdill
favicon: null
layout_spectrum: 0.866194628411904
typography_spectrum: 0.38573508244007826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8948270166292787
  lightness: 0.7317627628799528
  saturation: 0.7074755660723895
  rhythmicContrast: 0.9531189664267004
purpose: []
