name: Flooring by Cogdill
favicon: null
layout_spectrum: 0.25253
typography_spectrum: 0.50678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#de0202'
    - '#ffffff'
    - '#33669a'
    - '#000000'
    - '#b3b3b3'
  brandStrength: 0.625
  lightness: 0.7317627628799528
  saturation: 0.6875
  rhythmicContrast: 0.9531189664267004
purpose: []
